# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 郑子祥的博客 # ex. I m Chuan
name: Zeal Cheng # ex. DONGChuan
email: zealkitty@gmail.com
location: China GuangDong guangzhou # ex. Nice, France
company:
company_url:
github_url: https://github.com/ZealCheng # ex. https://github.com/DONGChuan
github_username: ZealCheng # ex. DONGChuan
description:
motto: A little better than yesterday
favicon: snoopy.png # Image must be in assets/images
repository: ZealCheng/zealcheng.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://blog.zealcheng.me

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: blog.zealcheng.me/bower_components/embed-js # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /projects
    label: Projects

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
# skill_keywords: true
# skill_software_keywords: [Python, MySQL]
# skill_web_keywords: [PHP, Swoole, Redis, MongoDB, HTML, CSS, JS, JQuery, Ajax, AngularJS]
